enum CardTint {
	NORMAL = 0xFFFFFF,
	HOVERED = 0xE5E5E5,
	GRABBED = 0xCCCCCC,
	INACTIVE = 0x555555,

	VALID_ALLY_TARGET = 0xBFFFBF,
	VALID_ENEMY_TARGET = 0xFFBFBF,
	VALID_ALLY_TARGET_HOVERED = 0x92FF92,
	VALID_ENEMY_TARGET_HOVERED = 0xFF9292,
}

export default CardTint
