<template>
	<div class="the-rules-list">
		<div class="rules-container">
			<h1>Game rules</h1>
			<p>
				State of Imbalance is a 1v1 Player versus Player (or Player versus AI) card collecting game. Each players enters the game with a
				deck they build using the cards they own (see <b>Decks</b>). Players take turns playing cards and interacting with the board with
				the goal of maximizing the total Power of their cards. Player with the highest combined Power wins the round.
			</p>
			<p>A player wins the game after gaining 2 round wins.</p>

			<h2>Deck building</h2>
			<p>
				Every deck contains a total of {{ cardLimitTotal - 1 }} cards, plus a Leader card. Choosing a leader card also locks the factions
				this deck belongs to. The cards that the player puts into their deck are all <i>Units</i>.
			</p>
			<p>The deck must include exactly the following number of cards:</p>
			<ul>
				<li>1 Leader card</li>
				<li>{{ goldenCardsLimit }} Legendary cards</li>
				<li>{{ silverCardsLimit }} Epic cards</li>
				<li>{{ bronzeCardsLimit }} Common cards</li>
			</ul>
			<p>Only one copy of a Legendary card may be included. Epic, however, may have up to 2 copies and commons - up to 3.</p>

			<h2>Cards & Game board</h2>
			<p>
				All cards are divided into two categories: Units and Spells. From the player's perspective, all the Unit cards they own are stored
				in their Unit hand (on the left), and Spells - in the Spell hand (on the right). Units are the cards the player put into their deck
				or the ones generated by other cards. Spells are always created by other cards, most typically - by selected Leaders.
			</p>
			<p>
				When played, Units take space on the game board. The board is split into 6 rows, with each player owning 3 closest to them. Each row
				may hold up to {{ unitsPerRow }} units. Row positioning is important to some of the card effects.
			</p>
			<p>
				Units have a certain Power value, represented by the number in the top left corner of the card. This is the value that is used to
				determine the total Power on the board at the end of the round. The card's Power may change during the course of the game by the
				means of taking damage, healing or applying status effects (buffs) to the card.
			</p>
			<p>
				Spells, on the other hand, are resolved immediately after being played and go into graveyard. Spells also require some Mana to play,
				represented by the number in the top left corner of the card. Player has 10 Mana to spend during the round, and some cards may
				generate more.
			</p>
			<p>
				Generally, player's spell hand contains a number of Leader Powers, determined by the leader selected. Unlike other spells, Leader
				Powers will return to the player's hand at the start of the next turn when used.
			</p>
			<p>
				Most cards in the game also have certain effects, described by their text. <b>Deploy</b> effects are the most common, and those are
				resolved as soon as the card is played onto the board.
			</p>

			<h2>Player's turn</h2>
			<p>During their turn, a player must either:</p>
			<ul>
				<li>Play exactly one card from their unit hand</li>
				<li>Finish their round</li>
			</ul>
			<p>
				When a player finishes their round, their opponent is still free to continue playing cards as long as they have cards to play. The
				winner of the round is determined when both players finish their round.
			</p>
			<p>On top of the basic action, player may also do the following during their turn:</p>
			<ul>
				<li>Play any <b>Temporary</b> cards</li>
				<li>Play spell cards as long as they have mana to pay the cost</li>
				<li>Issue orders to cards on the board that have the <b>Order</b> keyword</li>
			</ul>
		</div>
	</div>
</template>

<script lang="ts">
import Constants from '@shared/Constants'
import { defineComponent } from 'vue'

export default defineComponent({
	setup() {
		return {
			cardLimitTotal: Constants.CARD_LIMIT_TOTAL,
			goldenCardsLimit: Constants.CARD_LIMIT_GOLDEN,
			silverCardsLimit: Constants.CARD_LIMIT_SILVER,
			bronzeCardsLimit: Constants.CARD_LIMIT_BRONZE,
			unitsPerRow: Constants.MAX_CARDS_PER_ROW,
		}
	},
})
</script>

<style scoped lang="scss">
@import '../../styles/generic';

.the-rules-list {
	.rules-container {
		width: calc(100% - 64px);
		height: 100%;
		padding: 32px;
		overflow-y: auto;

		p {
			text-indent: 2em;
			text-align: left;
			line-height: 1.5em;
		}
		ul {
			padding-left: 4em;
			line-height: 1.5em;
			text-align: left;
		}
	}
}
</style>
