import BoardSplitMode from '../../enums/BoardSplitMode'

export type RulesetConstants = {
	ROUND_WINS_REQUIRED: number
	UNIT_HAND_SIZE_LIMIT: number
	UNIT_HAND_SIZE_STARTING: number
	UNIT_HAND_SIZE_PER_ROUND: number
	SPELL_HAND_SIZE_MINIMUM: number
	SPELL_HAND_SIZE_LIMIT: number
	SPELL_MANA_PER_ROUND: number

	FIRST_GROUP_MOVES_FIRST: boolean
	SECOND_GROUP_MOVES_FIRST: boolean

	SKIP_MULLIGAN: boolean
	MULLIGAN_INITIAL_CARD_COUNT: number
	MULLIGAN_ROUND_CARD_COUNT: number

	GAME_BOARD_ROW_COUNT: number
	GAME_BOARD_ROW_SPLIT_MODE: BoardSplitMode

	PASSIVE_LEADERS: boolean
}
