enum TargetType {
	UNIT,
	BOARD_ROW,

	PLAYER_CARD_IN_HAND,
	PLAYER_CARD_IN_DECK,
	PLAYER_CARD_IN_GRAVEYARD,

	OPPONENT_CARD_IN_HAND,
	OPPONENT_CARD_IN_DECK,
	OPPONENT_CARD_IN_GRAVEYARD
}

export default TargetType
