export default {
	PLAYERS_PER_GAME: 2,
	MAX_TIME_OF_DAY: 11,
	TIME_UNITS_PER_DAY: 12,
	STARTING_PLAYER_MORALE: 2,
	UNIT_HAND_SIZE_LIMIT: 25,
	UNIT_HAND_SIZE_STARTING: 10,
	UNIT_HAND_SIZE_PER_ROUND: 5,
	SPELL_HAND_SIZE_MINIMUM: 4,
	SPELL_HAND_SIZE_LIMIT: 10,
	SPELL_MANA_PER_ROUND: 10,
	MAX_CARDS_PER_ROW: 10,
	GAME_BOARD_ROW_COUNT: 6
}
