export default {
	PLAYERS_PER_GAME: 2,
	MAX_TIME_OF_DAY: 11,
	TIME_UNITS_PER_DAY: 12,
	STARTING_PLAYER_MORALE: 2,
	UNIT_HAND_SIZE_LIMIT: 30,
	UNIT_HAND_SIZE_STARTING: 10,
	UNIT_HAND_SIZE_PER_ROUND: 5,
	SPELL_HAND_SIZE_MINIMUM: 10,
	SPELL_HAND_SIZE_LIMIT: 10,
	SPELL_MANA_PER_ROUND: 10,
	MAX_CARDS_PER_ROW: 11,
	GAME_BOARD_ROW_COUNT: 6,

	CARD_LIMIT_LEADER: 1,
	CARD_LIMIT_GOLDEN: 4,
	CARD_LIMIT_SILVER: 10,
	CARD_LIMIT_BRONZE: 21,
	CARD_LIMIT_TOTAL: 1 + 4 + 10 + 21,

	CARD_COPIES_LIMIT_LEADER: 1,
	CARD_COPIES_LIMIT_GOLDEN: 1,
	CARD_COPIES_LIMIT_SILVER: 2,
	CARD_COPIES_LIMIT_BRONZE: 3,

	MULLIGAN_INITIAL_CARD_COUNT: 5,
	MULLIGAN_ROUND_CARD_COUNT: 3,

	COMPRESS_GAME_TRAFFIC: false,
}
