const Constants = {
	CREATE_KEYWORD_CARD_COUNT: 3,
	MAX_CARDS_PER_ROW: 11,

	CARD_LIMIT_LEADER: 1,
	CARD_LIMIT_GOLDEN: 4,
	CARD_LIMIT_SILVER: 6,
	CARD_LIMIT_BRONZE: 15,
	CARD_LIMIT_TOTAL: 1 + 4 + 6 + 15,

	CARD_COPIES_LIMIT_LEADER: 1,
	CARD_COPIES_LIMIT_GOLDEN: 1,
	CARD_COPIES_LIMIT_SILVER: 1,
	CARD_COPIES_LIMIT_BRONZE: 3,
}

export default Constants
