enum CardFeature {
	KEYWORD_DEPLOY,
	KEYWORD_TURN_START,
	KEYWORD_ENRAGE,
	KEYWORD_INFUSE_X,
	KEYWORD_INFUSE_ALL,
	KEYWORD_CREATE,
	KEYWORD_SUMMON,
	KEYWORD_DISCARD,
	HERO_POWER,
	TEMPORARY_CARD,
	LOW_SORT_PRIORITY
}

export default CardFeature
