enum CardTribe {
	BIRD = 'bird',
	BEAST = 'beast',
	DRYAD = 'dryad',
	NOBLE = 'noble',
	STORM = 'storm',
	SPARK = 'spark',
	SCROLL = 'scroll',
	DRAGON = 'dragon',
	CULTIST = 'cultist',
	SALVAGE = 'salvage',
	SOLDIER = 'soldier',
	MERFOLK = 'merfolk',
	BUILDING = 'building',
	COMMONER = 'commoner',
	VALKYRIE = 'valkyrie',
	ELEMENTAL = 'elemental',
	VOIDSPAWN = 'voidspawn',
	MANIFESTATION = 'manifestation',

	DRACONID = 'draconid',
	WILD_HUNT = 'wildHunt',
	CONSTRUCT = 'construct',
	MACHINE = 'machine',
	CURSED = 'cursed',
	VAMPIRE = 'vampire',
	NECROPHAGE = 'necrophage',
	BOON = 'BOON',
	HAZARD = 'HAZARD',

	LOST = 'lost',
	RITES_WEAPON = 'ritesWeapon',
	RITES_ARMOR = 'ritesArmor',
	RITES_GLOVES = 'ritesGloves',
	RITES_BOOTS = 'ritesBoots',
	RITES_TREASURE = 'ritesTreasure',
	LABYRINTH_BUCKET = 'ritesBucket',
}

export default CardTribe
