enum CardFeature {
	KEYWORD_DEPLOY,
	KEYWORD_TURN_START,
	KEYWORD_ENRAGE,
	KEYWORD_INFUSE_X,
	KEYWORD_INFUSE_ALL,
	KEYWORD_CREATE,
	KEYWORD_SUMMON,
	KEYWORD_DISCARD,
	KEYWORD_BUFF_STUN,
	KEYWORD_BUFF_GROWTH,
	KEYWORD_BUFF_STRENGTH,
	KEYWORD_BUFF_IMMUNITY,
	KEYWORD_BUFF_TEMPORARY_CARD,
	HERO_POWER,
	STUNNED,
	SUSPENDED,
	UNTARGETABLE,
	TEMPORARY_CARD,
	LOW_SORT_PRIORITY
}

export default CardFeature
