enum CardTribe {
	BIRD = 'bird',
	BEAST = 'beast',
	DRYAD = 'dryad',
	NOBLE = 'noble',
	STORM = 'storm',
	SPARK = 'spark',
	SCROLL = 'scroll',
	DRAGON = 'dragon',
	CULTIST = 'cultist',
	SALVAGE = 'salvage',
	SOLDIER = 'soldier',
	MERFOLK = 'merfolk',
	BUILDING = 'building',
	COMMONER = 'commoner',
	VALKYRIE = 'valkyrie',
	ELEMENTAL = 'elemental',
	VOIDSPAWN = 'voidspawn',
	MANIFESTATION = 'manifestation',

	LOST = 'lost',
	RITES_WEAPON = 'lab_weapon',
	RITES_ARMOR = 'lab_armor',
	RITES_GLOVES = 'lab_gloves',
	RITES_BOOTS = 'lab_boots',
	RITES_TREASURE = 'lab_treasure',
	LABYRINTH_BUCKET = 'lab_bucket',
}

export default CardTribe
