enum LeaderStatType {
	DIRECT_UNIT_DAMAGE,
	SPLASH_UNIT_DAMAGE,
	DIRECT_SPELL_DAMAGE,
	SPLASH_SPELL_DAMAGE,
	DIRECT_HEALING_POTENCY,
	SPLASH_HEALING_POTENCY,
	RECURRING_HEALING_POTENCY,
	DIRECT_BUFF_POTENCY,
	SPLASH_BUFF_POTENCY,
	RECURRING_BUFF_POTENCY,
	DIRECT_EFFECT_DURATION,
	SPLASH_EFFECT_DURATION,
	DIRECT_TARGET_COUNT,
	CRITICAL_DAMAGE_CHANCE,
	CRITICAL_BUFF_CHANCE,
	CRITICAL_HEAL_CHANCE,
	SPARK_DAMAGE,
}

export default LeaderStatType
